### ISSUE TITLE
Connection issue on remote host

### ISSUE THREAD

**Issue by 1915** [WedjaaOpen/ElasticJasperServer#1]
Connecting to a remote amazon ec2-instance from Jaspersoft Studio timeouts after 42-45 seconds with the message: "None of the configured nodes are available". Ports 9200-9400 are confirmed open. Tried commenting out the clustername in ES configuration to no avail.

Had the same problem with a previous computer - which suddenly started working, so I suspect an error on my part but I also found this on [stackoverflow](http://stackoverflow.com/questions/23348953/elasticsearch-no-node-available):

_"try to experiment with the client.transport.ping_timeout & client.transport.nodes_sampler_interval parameters of the transport client ( I assume you are using a transport client right?) and see observe how your app behaves."_

Here is the error log from Jaspersoft:

org.elasticsearch.client.transport.NoNodeAvailableException: None of the configured nodes are available: []
    at org.elasticsearch.client.transport.TransportClientNodesService.ensureNodesAreAvailable(TransportClientNodesService.java:278)
    at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:197)
    at org.elasticsearch.client.transport.support.InternalTransportClient.execute(InternalTransportClient.java:106)
    at org.elasticsearch.client.support.AbstractClient.search(AbstractClient.java:334)
    at org.elasticsearch.client.transport.TransportClient.search(TransportClient.java:424)
    at org.elasticsearch.action.search.SearchRequestBuilder.doExecute(SearchRequestBuilder.java:1116)
    at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:91)
    at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:65)
    at net.wedjaa.elasticparser.ESSearch.executeSearch(ESSearch.java:485)
    at net.wedjaa.elasticparser.ESSearch.runQuery(ESSearch.java:521)
    at net.wedjaa.elasticparser.ESSearch.runQuery(ESSearch.java:549)
    at net.wedjaa.elasticparser.ESSearch.getFields(ESSearch.java:602)
    at net.wedjaa.elasticparser.ESSearch.getFields(ESSearch.java:612)
    at net.wedjaa.elasticparser.ESSearch.test(ESSearch.java:619)
    at net.wedjaa.jasper.elasticsearch.adapter.ESAdapterService.test(ESAdapterService.java:114)
    at com.jaspersoft.studio.data.wizard.AbstractDataAdapterWizard$3.run(AbstractDataAdapterWizard.java:157)
    at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:121)

**Comment by 1915** [comment]
Could also be an issue with AWS: http://jontai.me/blog/2013/03/elasticsearch-ec2-discovery/

**Comment by 1915** [comment]
If anyone else is having the same issue with Amazon EC2-instances it's probably to fault with elasticsearch configuration: network.publish_host, which automatically sets the ip to a local host which is unreachable from the outside. Setting it to the actual ip solves the problem.

**Comment by Wedjaa** [comment]
Thank you for spotting this - can I close the issue?

**Comment by 1915** [comment]
Yes!
